### PR TITLE
finally corrected err3_cf1206C.txt

### PR DESCRIPTION
**Pull request by lav-joshi**

### CODE REVIEW

**Comment by masterchef2209** [comment]
still too many changes, the solution is already correct, it just has very minor bug which you have to spot, you don't have to change the structure of the solution.

**Comment by lav-joshi** [comment]
Yes sir
That i have only corrected
One was the previous one.....

**Comment by lav-joshi** [comment]
This much change only sir

**Comment by lav-joshi** [comment]
See the finally corrected err3 file

**Pull request closed without merging**
