### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by PreritSM**
end--- endl
continue has been cancelled

### CODE REVIEW

**Comment by masterchef2209** [comment]
Some changes are wrong, read problem statement again

**Comment by PreritSM** [comment]
The code runs perfectly in codetable(hackerearth)
end--- endl
continue;; has been removed
Screenshot 1
Screenshot 2

**Comment by masterchef2209** [comment]
Yes but it is still wrong, is it getting ACCEPTED on codeforces?

**Comment by PreritSM** [comment]
I haven't tried it

**Pull request closed without merging**
