### PR TITLE
solved err2_cf441C.txt(screenshots and code)

### PR DESCRIPTION
**Pull request by lav-joshi**

### CODE REVIEW

**Comment by lav-joshi** [comment]
![Screenshot from 2019-11-05 10-37-44]
(https://user-images.githubusercontent.com/54629424/68182745-4f416400-ffc0-11e9-96ac-ca4de7347dc1.png)
![Screenshot from 2019-11-05 10-37-49]
(https://user-images.githubusercontent.com/54629424/68182747-4f416400-ffc0-11e9-9cd8-084011174d04.png)

**Comment by masterchef2209** [comment]
already merged

**Comment by lav-joshi** [comment]
Err2 i have solved and sent

**Comment by lav-joshi** [comment]
by whom

**Pull request closed without merging**
